language: android
jdk: oraclejdk8

android:
 components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
 licenses:
  - android-sdk-license-.+
  - google-gdk-license-.+  
 
script:
 - chmod +x ./gradlew
 - ./gradlew assemble
 