language: android
jdk:
 -oraclejdk8
env:
 global:
   - ANDROID_ABI=26
   - EMULATOR_API=19
   - ANDROID_BUILD_TOOLS=26.0.2
   
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_ABI
  - android-$EMULATOR_API
  - addon-google_apis-google-19
  - extra-google-google_play_services
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-x86-android-19
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  

before_script:
 - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
 - emulator -avd test -no-skin -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 & 
   

script:
  - ./gradlew clean build connectedAndroidTest


  
