language: android
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.0
  - android-25
before_install:
  - chmod +x gradlew
script:
  - ./gradlew assembleRelease --stacktrace
