language: android

     
android:

  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - sys-img-armeabi-v7a-android-19
  - sys-img-armeabi-v7a-android-26
before_script:
  - chmod +x gradlew
  - android list targets
  - echo no | android create avd --force --name test --target android-26
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

before_install:
  - pip install --user codecov
  
script:
  - ./gradlew connectedAndroidTest -i
  - ./gradlew build checkstyle connectedCheck -PdisablePreDex

after_success:
  - codecov
  
