language: android
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
install:
  - cd app
  - ./gradlew build connectedCheck
script:
  - cd app
  - ./gradlew build connectedCheck 

  
 
