language: android
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.0
  - android-25
install:
  - cd app/
  - gradle build connectedCheck
script:
  - cd app
  - gradle build connectedCheck
