language: android

   
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-23.0.1
  - build-tools-25.0.2
  - build-tools-26.0.2
  - build-tools-26.1.1
  - android-4
  - android-10
  - android 19
  - android 23
  - android 25
  - android-26
  - extra-google-m2repository
  - extra-google-google_play_services
  - extra-android-m2repository
  - sys-img-x86-android-26
  - sys-img-armeabi-v7a-android-25
  - sys-img-armeabi-v7a-android-26
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
 
env:
    matrix:
        - ANDROID_TARGET=android-4 ANDROID_ABI=armeabi
        - ANDROID_TARGET=android-10 ANDROID_ABI=armeabi
        - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-26 ANDROID_ABI=armeabi-v7a-android-26
  
before_script:
 - android list targets
 - jdk_switcher use oraclejdk8
 - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI 
 - emulator -avd test -no-skin -no-audio -no-window &
 - android-wait-for-device
 - adb shell input keyevent 82 & 
   

script:
  - ./gradlew clean installDebug
  - ./gradlew check
  - ./gradlew testDebugUnitTest
  - ./gradlew connectedDebugAndroidTest


  
