language: android
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.1.0
  - android-26
install:
  - cd app/
  - gradle build connectedCheck
script:
  - cd app
  - gradle build connectedCheck
