language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-android-m2repository
install:
  - cd app
  - ./gradlew build connectedCheck
script:
  - cd app
  - ./gradlew build connectedCheck 

  
 
